-- Kitchen Made Health product catalog and health category upgrade.
-- Run after 20260723_editorial_workspace.sql.

create extension if not exists "pgcrypto";

-- Preserve any existing article assignments while retiring the old navigation
-- categories. Categories may already exist under the intended name, intended
-- slug, or an older slug, so resolve both unique constraints before normalizing.
-- This migration is safe to rerun and never orphans assigned posts.
do $$
declare
  name_match_id uuid;
  slug_match_id uuid;
  target_id uuid;
  source_id uuid;
begin
  select id into name_match_id
  from public.categories
  where name = 'Diabetes & blood sugar';

  select id into slug_match_id
  from public.categories
  where slug = 'diabetes-blood-sugar';

  if name_match_id is null and slug_match_id is null then
    insert into public.categories (name, slug, description)
    values (
      'Diabetes & blood sugar',
      'diabetes-blood-sugar',
      'Practical, evidence-aware guidance for steadier blood sugar, nourishing meals, and everyday diabetes care.'
    )
    returning id into target_id;
  elsif name_match_id is not null
    and slug_match_id is not null
    and name_match_id <> slug_match_id then
    update public.posts set category_id = slug_match_id where category_id = name_match_id;
    delete from public.categories where id = name_match_id;
    target_id := slug_match_id;
  else
    target_id := coalesce(slug_match_id, name_match_id);
  end if;

  update public.categories
  set
    name = 'Diabetes & blood sugar',
    slug = 'diabetes-blood-sugar',
    description = 'Practical, evidence-aware guidance for steadier blood sugar, nourishing meals, and everyday diabetes care.'
  where id = target_id;

  select id into source_id
  from public.categories
  where slug = 'cookware' and id <> target_id;

  if source_id is not null then
    update public.posts set category_id = target_id where category_id = source_id;
    delete from public.categories where id = source_id;
  end if;

  name_match_id := null;
  slug_match_id := null;
  target_id := null;
  source_id := null;

  select id into name_match_id
  from public.categories
  where name = 'Home remedies';

  select id into slug_match_id
  from public.categories
  where slug = 'home-remedies';

  if name_match_id is null and slug_match_id is null then
    insert into public.categories (name, slug, description)
    values (
      'Home remedies',
      'home-remedies',
      'Gentle, kitchen-rooted home remedies with clear limits, sensible precautions, and realistic expectations.'
    )
    returning id into target_id;
  elsif name_match_id is not null
    and slug_match_id is not null
    and name_match_id <> slug_match_id then
    update public.posts set category_id = slug_match_id where category_id = name_match_id;
    delete from public.categories where id = name_match_id;
    target_id := slug_match_id;
  else
    target_id := coalesce(slug_match_id, name_match_id);
  end if;

  update public.categories
  set
    name = 'Home remedies',
    slug = 'home-remedies',
    description = 'Gentle, kitchen-rooted home remedies with clear limits, sensible precautions, and realistic expectations.'
  where id = target_id;

  select id into source_id
  from public.categories
  where slug = 'kitchen-guides' and id <> target_id;

  if source_id is not null then
    update public.posts set category_id = target_id where category_id = source_id;
    delete from public.categories where id = source_id;
  end if;
end;
$$;

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  created_by uuid not null references auth.users(id) on delete cascade,
  name text not null check (char_length(name) between 2 and 140),
  details text not null check (char_length(details) between 10 and 800),
  price text not null check (char_length(price) between 1 and 40),
  image_url text not null,
  image_alt text check (char_length(image_alt) <= 180),
  affiliate_url text not null,
  button_label text not null default 'View product'
    check (char_length(button_label) between 2 and 60),
  active boolean not null default true,
  featured boolean not null default false,
  sort_order integer not null default 0 check (sort_order between 0 and 9999),
  click_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.product_clicks (
  id bigint generated by default as identity primary key,
  product_id uuid not null references public.products(id) on delete cascade,
  clicked_at timestamptz not null default now()
);

create index if not exists idx_products_public_order
  on public.products(active, featured desc, sort_order, created_at desc);
create index if not exists idx_products_owner
  on public.products(created_by, updated_at desc);
create index if not exists idx_product_clicks_date
  on public.product_clicks(clicked_at desc);

create or replace function public.set_product_timestamps()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_product_timestamps on public.products;
create trigger trg_product_timestamps
  before update on public.products
  for each row execute function public.set_product_timestamps();

create or replace function public.track_product_click(target_product_id uuid)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_url text;
begin
  select affiliate_url into target_url
  from public.products
  where id = target_product_id and active = true;

  if target_url is null then
    return null;
  end if;

  insert into public.product_clicks (product_id) values (target_product_id);
  update public.products
  set click_count = click_count + 1
  where id = target_product_id;

  return target_url;
end;
$$;

revoke all on function public.track_product_click(uuid) from public;
grant execute on function public.track_product_click(uuid) to anon, authenticated;

alter table public.products enable row level security;
alter table public.product_clicks enable row level security;

drop policy if exists "products_public_read" on public.products;
create policy "products_public_read" on public.products for select
  using (active = true or created_by = auth.uid());

drop policy if exists "products_author_insert" on public.products;
create policy "products_author_insert" on public.products for insert
  to authenticated with check (created_by = auth.uid());

drop policy if exists "products_author_update" on public.products;
create policy "products_author_update" on public.products for update
  to authenticated using (created_by = auth.uid()) with check (created_by = auth.uid());

drop policy if exists "products_author_delete" on public.products;
create policy "products_author_delete" on public.products for delete
  to authenticated using (created_by = auth.uid());

drop policy if exists "product_clicks_editor_read" on public.product_clicks;
create policy "product_clicks_editor_read" on public.product_clicks for select
  to authenticated using (true);

insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do update set public = true;

drop policy if exists "public_read_product_images" on storage.objects;
create policy "public_read_product_images"
  on storage.objects for select
  using (bucket_id = 'product-images');

drop policy if exists "authenticated_upload_product_images" on storage.objects;
create policy "authenticated_upload_product_images"
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'product-images');

drop policy if exists "authenticated_update_product_images" on storage.objects;
create policy "authenticated_update_product_images"
  on storage.objects for update
  to authenticated
  using (bucket_id = 'product-images')
  with check (bucket_id = 'product-images');

drop policy if exists "authenticated_delete_product_images" on storage.objects;
create policy "authenticated_delete_product_images"
  on storage.objects for delete
  to authenticated
  using (bucket_id = 'product-images');
