-- Kitchen Made Health editorial workspace upgrade
-- Safe to run after supabase/schema.sql.

create extension if not exists "pgcrypto";

alter table public.posts
  add column if not exists primary_keyword text,
  add column if not exists cover_image_alt text;

alter table public.posts drop constraint if exists posts_status_check;
alter table public.posts
  add constraint posts_status_check
  check (status in ('draft', 'scheduled', 'published'));

create table if not exists public.tags (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  slug text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.post_tags (
  post_id uuid not null references public.posts(id) on delete cascade,
  tag_id uuid not null references public.tags(id) on delete cascade,
  primary key (post_id, tag_id)
);

create table if not exists public.post_revisions (
  id uuid primary key default gen_random_uuid(),
  post_id uuid not null references public.posts(id) on delete cascade,
  author_id uuid not null references auth.users(id) on delete cascade,
  snapshot jsonb not null,
  source text not null default 'manual'
    check (source in ('autosave', 'manual', 'restore', 'publish')),
  created_at timestamptz not null default now()
);

create table if not exists public.affiliate_links (
  id uuid primary key default gen_random_uuid(),
  post_id uuid not null references public.posts(id) on delete cascade,
  product_name text not null,
  merchant text not null default 'Amazon',
  destination_url text not null,
  button_label text not null default 'View product',
  disclosure text,
  click_count integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.affiliate_clicks (
  id bigint generated by default as identity primary key,
  affiliate_link_id uuid not null references public.affiliate_links(id) on delete cascade,
  clicked_at timestamptz not null default now()
);

create table if not exists public.post_views (
  id bigint generated by default as identity primary key,
  post_id uuid not null references public.posts(id) on delete cascade,
  viewed_at timestamptz not null default now()
);

create table if not exists public.newsletter_subscribers (
  id uuid primary key default gen_random_uuid(),
  email text not null unique,
  status text not null default 'active' check (status in ('active', 'unsubscribed')),
  source text not null default 'website',
  subscribed_at timestamptz not null default now()
);

create table if not exists public.comments (
  id uuid primary key default gen_random_uuid(),
  post_id uuid not null references public.posts(id) on delete cascade,
  author_name text not null,
  author_email text not null,
  body text not null check (char_length(body) between 2 and 2000),
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'spam')),
  created_at timestamptz not null default now(),
  moderated_at timestamptz
);

create table if not exists public.activity_log (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_posts_admin_filters
  on public.posts(status, category_id, updated_at desc);
create index if not exists idx_posts_scheduled
  on public.posts(published_at) where status = 'scheduled';
create index if not exists idx_post_tags_tag on public.post_tags(tag_id);
create index if not exists idx_post_revisions_post_created
  on public.post_revisions(post_id, created_at desc);
create index if not exists idx_affiliate_links_post on public.affiliate_links(post_id);
create index if not exists idx_affiliate_clicks_date
  on public.affiliate_clicks(clicked_at desc);
create index if not exists idx_post_views_date
  on public.post_views(viewed_at desc);
create index if not exists idx_post_views_post_date
  on public.post_views(post_id, viewed_at desc);
create index if not exists idx_comments_status_date
  on public.comments(status, created_at desc);
create index if not exists idx_activity_date
  on public.activity_log(created_at desc);

create or replace function public.set_post_timestamps()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();

  if new.status = 'published'
     and (old.status is distinct from 'published' or new.published_at is null) then
    new.published_at = now();
  elsif new.status = 'draft' then
    new.published_at = null;
  end if;

  return new;
end;
$$;

create or replace function public.trim_post_revisions()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  delete from public.post_revisions
  where post_id = new.post_id
    and id not in (
      select id
      from public.post_revisions
      where post_id = new.post_id
      order by created_at desc
      limit 20
    );
  return new;
end;
$$;

drop trigger if exists trg_trim_post_revisions on public.post_revisions;
create trigger trg_trim_post_revisions
  after insert on public.post_revisions
  for each row execute function public.trim_post_revisions();

create or replace function public.publish_scheduled_posts()
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  published_count integer;
begin
  update public.posts
  set status = 'published'
  where status = 'scheduled'
    and published_at is not null
    and published_at <= now();

  get diagnostics published_count = row_count;
  return published_count;
end;
$$;

create or replace function public.track_post_view(target_post_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.post_views (post_id) values (target_post_id);
  update public.posts
  set view_count = view_count + 1
  where id = target_post_id and status = 'published';
end;
$$;

create or replace function public.track_affiliate_click(target_link_id uuid)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_url text;
begin
  select destination_url into target_url
  from public.affiliate_links
  where id = target_link_id and active = true;

  if target_url is null then
    return null;
  end if;

  insert into public.affiliate_clicks (affiliate_link_id)
  values (target_link_id);

  update public.affiliate_links
  set click_count = click_count + 1, updated_at = now()
  where id = target_link_id;

  return target_url;
end;
$$;

revoke all on function public.publish_scheduled_posts() from public;
grant execute on function public.publish_scheduled_posts() to authenticated, service_role;
grant execute on function public.track_post_view(uuid) to anon, authenticated;
grant execute on function public.track_affiliate_click(uuid) to anon, authenticated;

alter table public.tags enable row level security;
alter table public.post_tags enable row level security;
alter table public.post_revisions enable row level security;
alter table public.affiliate_links enable row level security;
alter table public.affiliate_clicks enable row level security;
alter table public.post_views enable row level security;
alter table public.newsletter_subscribers enable row level security;
alter table public.comments enable row level security;
alter table public.activity_log enable row level security;

drop policy if exists "tags_public_read" on public.tags;
create policy "tags_public_read" on public.tags for select using (true);
drop policy if exists "tags_editor_write" on public.tags;
create policy "tags_editor_write" on public.tags for all to authenticated
  using (true) with check (true);

drop policy if exists "post_tags_public_read" on public.post_tags;
create policy "post_tags_public_read" on public.post_tags for select using (true);
drop policy if exists "post_tags_editor_write" on public.post_tags;
create policy "post_tags_editor_write" on public.post_tags for all to authenticated
  using (true) with check (true);

drop policy if exists "revisions_author_read" on public.post_revisions;
create policy "revisions_author_read" on public.post_revisions for select to authenticated
  using (author_id = auth.uid());
drop policy if exists "revisions_author_insert" on public.post_revisions;
create policy "revisions_author_insert" on public.post_revisions for insert to authenticated
  with check (author_id = auth.uid());

drop policy if exists "affiliate_public_read" on public.affiliate_links;
create policy "affiliate_public_read" on public.affiliate_links for select
  using (active = true or auth.role() = 'authenticated');
drop policy if exists "affiliate_editor_write" on public.affiliate_links;
create policy "affiliate_editor_write" on public.affiliate_links for all to authenticated
  using (true) with check (true);

drop policy if exists "affiliate_clicks_editor_read" on public.affiliate_clicks;
create policy "affiliate_clicks_editor_read" on public.affiliate_clicks for select to authenticated
  using (true);

drop policy if exists "post_views_editor_read" on public.post_views;
create policy "post_views_editor_read" on public.post_views for select to authenticated
  using (true);

drop policy if exists "subscribers_public_insert" on public.newsletter_subscribers;
create policy "subscribers_public_insert" on public.newsletter_subscribers for insert
  to anon, authenticated with check (true);
drop policy if exists "subscribers_editor_manage" on public.newsletter_subscribers;
create policy "subscribers_editor_manage" on public.newsletter_subscribers for all
  to authenticated using (true) with check (true);

drop policy if exists "comments_public_read_approved" on public.comments;
create policy "comments_public_read_approved" on public.comments for select
  using (status = 'approved' or auth.role() = 'authenticated');
drop policy if exists "comments_public_insert" on public.comments;
create policy "comments_public_insert" on public.comments for insert
  to anon, authenticated with check (status = 'pending');
drop policy if exists "comments_editor_manage" on public.comments;
create policy "comments_editor_manage" on public.comments for all
  to authenticated using (true) with check (true);

drop policy if exists "activity_editor_read" on public.activity_log;
create policy "activity_editor_read" on public.activity_log for select
  to authenticated using (true);
drop policy if exists "activity_editor_insert" on public.activity_log;
create policy "activity_editor_insert" on public.activity_log for insert
  to authenticated with check (actor_id = auth.uid());

-- Optional Supabase Cron schedule (enable pg_cron in Database > Extensions first):
-- select cron.schedule(
--   'publish-kmh-scheduled-posts',
--   '* * * * *',
--   $$select public.publish_scheduled_posts();$$
-- );
